name: Add readthedocs preview links to PR descriptions

on:
  pull_request_target:
    types:
      - opened
    paths:
      - "docs/**"

jobs:
  pull-request-links:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "test-multilingual-sphinx"
